name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Rhythm.sln

      - name: Build
        run: dotnet build Rhythm.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Rhythm.sln --configuration Release --no-build
